services:
  fastapi:
    image: fastapi_sample_api
    container_name: api
    ports:
      - 8000:8000
    networks:
      - backend
  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - backend

networks:
  backend:
    driver: bridge