services:
  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres:/var/lib/postgresql/data
  fastapi:
    build:
      context: fastapi/
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 8000:8000